---

- name: Install extra yum repos
  become: true
  yum:
    name: epel-release
    state: present

- name: Install nginx
  become: true
  yum:
    name: nginx
    state: present
  notify:
    - PingNginx
 
