---

- name: Install extra yum repos
  become: true
  yum:
    name: epel-release
    state: present

- name: Install nginx
  become: true
  yum:
    name: nginx
    state: present
  notify:
    - PingNginx
 

#- name: ding nginx
#  become: true
#  service: 
#    name: nginx 
#    state: started 
#    use: service

#- name: yo Nginx
#  become: true
#  systemctl: 
#    name: nginx.service
#    state: started
